### PR TITLE
Fix avanza_socket.py's __create_socket to work with latest websockets version

### LINKED ISSUE #132: regression: latest websockets dependency breaks subscribe_to_id
Installing `avanza-api` will in turn install a breaking version of the [websockets](https://websockets.readthedocs.io) dependency. [avanza/setup.py](https://github.com/Qluxzz/avanza/blob/master/setup.py#L23) doesn't enforce a version of websockets other than > 8:
`REQUIRED = ["requests>=2", "pyotp>=2", "websockets>=8", "pydantic>=2"]`.

The latest version of websockets (14.2) has [updated the keyword arg for extra headers](https://websockets.readthedocs.io/en/stable/faq/client.html#how-do-i-set-http-headers) that is used in [avanza_socket.py:47](https://github.com/Qluxzz/avanza/blob/master/avanza/avanza_socket.py#L47). This results in `got an unexpected keyword argument 'extra_headers'` error when calling e.g. `await avanza.subscribe_to_id(ChannelType.ORDERDEPTHS, order_book_id, callback)`:

```
future: <Task finished name='Task-13' coro=<AvanzaSocket.__create_socket() done, defined at /usr/local/lib/python3.11/site-packages/avanza/avanza_socket.py:45> exception=TypeError("BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/avanza/avanza_socket.py", line 46, in __create_socket
    async with websockets.connect(
```

The bug is possibly related to #127 as well. Haven't replicated that though.

### Fix
- old: `async with websockets.connect(WEBSOCKET_URL, extra_headers={"Cookie": self._cookies}) as self._socket:`
- new: `async with websockets.connect(WEBSOCKET_URL, additional_headers={"Cookie": self._cookies}) as self._socket:`

### PR DESCRIPTION
**Pull request by lilfelix**
Closes #132 by replacing `async with websockets.connect(WEBSOCKET_URL, extra_headers={"Cookie": self._cookies}) as self._socket:` with `async with websockets.connect(WEBSOCKET_URL, additional_headers={"Cookie": self._cookies}) as self._socket:`

### CODE REVIEW

**Comment by Qluxzz** [comment]
The major change in websockets version 14 seems to be that they have changed the default implementation. But the new implementation has been available since version 13.

The old implementation which had the `extra_headers` param has been moved to `websockets.legacy.client`.

I have been testing out websocket versions from 8, which the setup.py defines as lowest required version (which doesn't work).

From what I can see the current code works with a websocket version of at least >= 11.0.0, and then stops working in version 14.0.0 because of the switch default implementation.

The simplest solution I see to have the most compatibility is doing the following:

```python
try:
    import websockets.legacy.client as websockets
except:
    import websockets
```

Which if the legacy version is available (will be removed 2030), use the legacy implementation, otherwise the version is below 13, use the original namespace.

That way anyone using websockets >= 11.0.0 can expect it to work until 2030 when we need to migrate to the new version, but in 2030 that will have been the default implementation since 2024 so hopefully most have migrated to it.

**Comment by lilfelix** [comment]
Okay I see. Am I understanding you correctly that we should modify `setup.py` to require a websocket version of at least >= 11.0.0 regardless? If so, how about this snippet to ensure the correct client is used?
```
import sys
from importlib.metadata import version, PackageNotFoundError

try:
    ws_version = tuple(map(int, version("websockets").split(".")))
except PackageNotFoundError:
    sys.exit("Error: The 'websockets' package is not installed.")

if ws_version < (11, 0, 0):
    sys.exit("Error: websockets version must be >= 11.0.0")
elif (11, 0, 0) <= ws_version < (14, 0, 0):
    from websockets.legacy.client import connect as websockets_connect
else:  # 14.0.0 and above
    from websockets import connect as websockets_connect
```
 `importlib.metadata.version()` is available since Python 3.8+

**Comment by Qluxzz** [comment]
Yeah, we will have to change the minimum required version of websockets in setup.py regardless since only >= 11 works.

I retested this just to be sure and the namespace `websockets.legacy.client` was already present in websockets version 11 so the only thing that needs to be changed to fix the issue is just updating the import:

`import websockets.legacy.client as websockets`, and nothing else will need to be changed.

I've tested this with websockets version 11, 12, 13, 14, and 15 and they all work with just this change.

**Comment by Qluxzz** [comment]
I have implemented the change mentioned above and released it with version 15.1.0, thanks for raising the PR and prompting the investigation of the issue.
